# Deployment Manifest for ArgoCD application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-applications
  namespace: argocd

spec:
  project: default
  source:
    repoURL: git@github.com:Leke-Ariyo/k8deployments.git
    targetRevision: HEAD
    path: development/argocd-apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
